// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Navigation Header documents */
interface NavigationHeaderDocumentData {
    /**
     * Desktop | Logo field in *Navigation Header*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_header.desktop_logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    desktop_logo: prismicT.ImageField<never>;
    /**
     * Mobile | Logo field in *Navigation Header*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_header.mobile_logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    mobile_logo: prismicT.ImageField<never>;
    /**
     * Show Search field in *Navigation Header*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: navigation_header.show_search
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    show_search: prismicT.BooleanField;
    /**
     * Slice Zone field in *Navigation Header*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_header.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavigationHeaderDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation Header → Slice Zone*
 *
 */
type NavigationHeaderDocumentDataSlicesSlice = NavigationItemSlice;
/**
 * Navigation Header document from Prismic
 *
 * - **API ID**: `navigation_header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationHeaderDocument<Lang extends string = string> =
    prismicT.PrismicDocumentWithoutUID<
        Simplify<NavigationHeaderDocumentData>,
        "navigation_header",
        Lang
    >;
export type AllDocumentTypes = NavigationHeaderDocument;
/**
 * Primary content in NavigationItem → Primary
 *
 */
interface NavigationItemSliceDefaultPrimary {
    /**
     * Navigation Item | Text field in *NavigationItem → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.primary.navigation_item_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    navigation_item_text: prismicT.KeyTextField;
    /**
     * Navigation Item | URL field in *NavigationItem → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.primary.navigation_item_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    navigation_item_url: prismicT.LinkField;
}
/**
 * Item in NavigationItem → Items
 *
 */
export interface NavigationItemSliceDefaultItem {
    /**
     * Mega Menu Item | Link field in *NavigationItem → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.items[].mega_menu_item_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    mega_menu_item_link: prismicT.LinkField;
    /**
     * Mega Menu Item | Image field in *NavigationItem → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.items[].mega_menu_item_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    mega_menu_item_image: prismicT.ImageField<never>;
    /**
     * Mega Menu Item | Text field in *NavigationItem → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.items[].mega_menu_item_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    mega_menu_item_text: prismicT.KeyTextField;
}
/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSliceDefault = prismicT.SharedSliceVariation<
    "default",
    Simplify<NavigationItemSliceDefaultPrimary>,
    Simplify<NavigationItemSliceDefaultItem>
>;
/**
 * Slice variation for *NavigationItem*
 *
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;
/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSlice = prismicT.SharedSlice<
    "navigation_item",
    NavigationItemSliceVariation
>;
declare module "@prismicio/client" {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig,
        ): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type {
            NavigationHeaderDocumentData,
            NavigationHeaderDocumentDataSlicesSlice,
            NavigationHeaderDocument,
            AllDocumentTypes,
            NavigationItemSliceDefaultPrimary,
            NavigationItemSliceDefaultItem,
            NavigationItemSliceDefault,
            NavigationItemSliceVariation,
            NavigationItemSlice,
        };
    }
}
