#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo '======================================================='
echo '🚀 formatting codebase'
echo '======================================================='
yarn prettier
echo '======================================================='
echo '🚀 Checking production build'
echo '======================================================='
yarn build
git add .
